public enum SoundEffect
{
    None,
    ButtonClick,
    TowerBuilt,
    TowerDeleted,
    GoblinDeath,
    DragonDeath,
    GolemDeath,
    ArrowFire,
    WaveClear,
    AreaAttack,
    BuildLevelUp,
    LaserBeam,
    CoinGet,
    ProjImpact,
    SpellCast,
    DiceRoll,
    Explode,
    ProjLaunch,
    RareTower,
    RarestTower
}
